@baseUrl = http://localhost:8080
@ALICE_TOKEN = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZSIsImlhdCI6MTc4ODc5NDk1OCwiZXhwIjoxNzg4ODgxMzU4fQ.qLP3MbB3uIJFLNH2FUqw7mX62Y-XFZcS87bnAgvquDA
@BOB_TOKEN = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJib2IiLCJpYXQiOjE3ODg3OTUwMzAsImV4cCI6MTc4ODg4MTQzMH0.KLm2Z5JTCWGopZhiRaPuE0c8orpnzfvMEfIXW81qeXU


### =========================
### ORGANIZATION
### =========================

### Create Organization "Acme Corp"
POST {{baseUrl}}/api/v1/organizations
Content-Type: application/json
Authorization: Bearer {{ALICE_TOKEN}}

{
  "name": "Acme Corp",
  "slug": "acme-corp"
}
###