import type { ReactNode } from 'react'
import { Bell, ChevronDown, CircleHelp, Menu, X } from 'lucide-react'
import type { NavKey } from '../services/api'

export const navItems: { key: NavKey; label: string; count?: string; tag?: string }[] = [
  { key: 'overview', label: 'Overview' }, { key: 'projects', label: 'Projects', count: '14' }, { key: 'tasks', label: 'Tasks & Boards' }, { key: 'team', label: 'Team & Access', tag: 'RBAC' }, { key: 'settings', label: 'Org Settings' }, { key: 'audit', label: 'API & Audit Logs' },
]

export function Button({ children, variant = 'primary', onClick, className = '', type = 'button' }: { children: ReactNode; variant?: 'primary' | 'secondary' | 'ghost' | 'danger'; onClick?: () => void; className?: string; type?: 'button' | 'submit' }) { return <button type={type} className={`epm-button epm-button-${variant} ${className}`} onClick={onClick}>{children}</button> }
export function Badge({ children, tone = 'blue' }: { children: ReactNode; tone?: 'blue' | 'green' | 'gray' | 'red' | 'amber' }) { return <span className={`epm-badge epm-badge-${tone}`}>{children}</span> }
export function Progress({ value }: { value: number }) { return <div className="progress"><span style={{ width: `${value}%` }} /></div> }
export function Panel({ title, subtitle, children, className = '', action }: { title?: ReactNode; subtitle?: ReactNode; children: ReactNode; className?: string; action?: ReactNode }) { return <section className={`panel ${className}`}><div className="panel-title">{title && <div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>}{action}</div>{children}</section> }

export function AppShell({ active, onNavigate, children }: { active: NavKey; onNavigate: (key: NavKey) => void; children: ReactNode }) {
  return <div className="epm-app"><aside className="app-sidebar"><div className="sidebar-brand"><span className="brand-mark">M</span><div><strong>MY-EPM</strong><small>Multi-Tenant Core</small></div></div><button className="workspace-switcher"><span className="workspace-avatar">A</span><span><b>Acme FinTech Corp</b><small>/acme-fintech</small></span><ChevronDown size={13} /></button><span className="sidebar-section-label">Operations</span><nav>{navItems.slice(0, 4).map((item) => <button key={item.key} className={active === item.key ? 'active' : ''} onClick={() => onNavigate(item.key)}><span>{item.label}</span>{item.count && <b>{item.count}</b>}{item.tag && <em>{item.tag}</em>}</button>)}</nav><span className="sidebar-section-label">Administration</span><nav>{navItems.slice(4).map((item) => <button key={item.key} className={active === item.key ? 'active' : ''} onClick={() => onNavigate(item.key)}><span>{item.label}</span></button>)}</nav><div className="sidebar-user"><span className="user-avatar">KS</span><div><b>Kalli S.</b><small>Global Admin</small></div></div></aside><div className="app-content"><header className="topbar"><button className="menu-button" aria-label="Open navigation"><Menu size={17} /></button><div className="crumb">Acme Financial　/　<b>Console</b>　/　Multi-Tenant Enterprise Cluster</div><div className="top-actions"><input placeholder="Search tasks, comments, members" aria-label="Global search" /><span className="tenant-pill">Acme FinTech <b>OWNER</b></span><Bell size={15} /><CircleHelp size={15} /></div></header>{children}</div></div>
}
export function PageHeader({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: ReactNode }) { return <div className="page-context"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="page-actions">{actions}</div></div> }
export function MetricGrid({ metrics }: { metrics: { label: string; value: string; detail: string }[] }) { return <div className="metric-grid">{metrics.map((metric) => <div className="metric-card" key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.detail}</small></div>)}</div> }
export function DataRows({ rows }: { rows: { title: string; detail: string; status?: string; progress?: number }[] }) { return <div className="data-rows">{rows.map((row) => <div className="data-row" key={row.title}><div><strong>{row.title}</strong><small>{row.detail}</small></div>{row.progress !== undefined && <div className="row-progress"><b>{row.progress}%</b><Progress value={row.progress} /></div>}{row.status && <Badge tone="blue">{row.status}</Badge>}<Button variant="ghost">View</Button></div>)}</div> }
export function Footer() { return <footer className="app-footer"><span>MY-EPM Suite　© 2024 Acme FinTech Corp. All rights reserved.</span><span>Compliance Matrix　 API Spec　 System Status</span></footer> }
export function PublicFrame({ children }: { children: ReactNode }) { return <div className="public-frame"><div className="public-brand"><span className="brand-mark">M</span><b>MY-EPM</b><small>Multi-Tenant Core</small><nav>Features　 Architecture　 Security & S.P.L.　 Pricing　 Testimonials　 Docs</nav><span>Sign In　 <Badge>Get Started</Badge></span></div>{children}<Footer /></div> }
export function FormField({ label, value, type = 'text' }: { label: string; value?: string; type?: string }) { return <label className="form-field"><span>{label}</span><input type={type} defaultValue={value} /></label> }
export function EmptyIcon() { return <X size={12} aria-hidden="true" /> }
